export const TRANSACTION_STATUS = {
    APPROVED: "APPROVED",
    DECLINED: "DECLINED",
    PENDING: "PENDING",
    CANCELLED: "CANCELLED",
    IN_REVIEW: "IN_REVIEW",
}

export const TRANSACTION_ORIGIN = {
    MOBILE_APP: "MOBILE_APP",
    WEB_PORTAL: "WEB_PORTAL",
    IN_PERSON: "IN_PERSON",
    ATM_MACHINE: "ATM_MACHINE",
    PHONE_CALL: "PHONE_CALL",
}